### PR TITLE
Master

### PR DESCRIPTION
**Pull request by DeviantInterface**
Added 3 Phrases

### CODE REVIEW

**Comment by DeviantInterface** [comment]
Gracis. Enjoy, do I need to sync??

On Tue, May 12, 2015 at 3:50 PM, Rodrigo Graça <notifications@github.com>
wrote:

> Merged #9 <https://github.com/rodrigograca31/Samaritan/pull/9>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#event-303226729>.
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
It's always better to sync to have the latest changes. :smile:

**Comment by DeviantInterface** [comment]
Alright, thanks. [?]

On Tue, May 12, 2015 at 4:00 PM, Rodrigo Graça <notifications@github.com>
wrote:

> It's always better to sync to have the latest changes. [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-101418690>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
BTW, I just committed a little thing (background effect)

**Comment by DeviantInterface** [comment]
I don't see it showing up on the site, and on the client, it says:

On Tue, May 12, 2015 at 4:01 PM, Deviant Interface <
halokid687doesminecraft@gmail.com> wrote:

> Alright, thanks. [?]
>
> On Tue, May 12, 2015 at 4:00 PM, Rodrigo Graça <notifications@github.com>
> wrote:
>
>> It's always better to sync to have the latest changes. [image: :smile:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-101418690>
>> .
>>
>
>
>
> --
> ///Deviant
> Name: Mccree, Daniel P.
> SSN: XXX-XX-2840
> Designation: Threat To System
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
What site are you using? This is the "official" site: http://rodrigograca31.github.io/Samaritan/
If you can't see a darker color on the corners (effect) press CTRL + SHIFT + R (on Chrome), it clears cache and reloads the page.

**Comment by DeviantInterface** [comment]
I'm using that site.

On Tue, May 12, 2015 at 4:07 PM, Rodrigo Graça <notifications@github.com>
wrote:

> What site are you using? This is the "official" site:
> http://rodrigograca31.github.io/Samaritan/
> If you can't see a darker color on the corners (effect) press CTRL + SHIFT
> + R (on Chrome), it clears cache and reloads the page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-101421305>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by DeviantInterface** [comment]
I'm still not seeing it... But the update is AWESOME

On Tue, May 12, 2015 at 4:09 PM, Deviant Interface <
halokid687doesminecraft@gmail.com> wrote:

> I'm using that site.
>
> On Tue, May 12, 2015 at 4:07 PM, Rodrigo Graça <notifications@github.com>
> wrote:
>
>> What site are you using? This is the "official" site:
>> http://rodrigograca31.github.io/Samaritan/
>> If you can't see a darker color on the corners (effect) press CTRL +
>> SHIFT + R (on Chrome), it clears cache and reloads the page.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-101421305>
>> .
>>
>
>
>
> --
> ///Deviant
> Name: Mccree, Daniel P.
> SSN: XXX-XX-2840
> Designation: Threat To System
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
Before:

After:

**Comment by DeviantInterface** [comment]
One thing. The bottom triangle is to big on Mobile Versions

On Wed, May 13, 2015 at 8:14 AM, Rodrigo Graça <notifications@github.com>
wrote:

> Before:
>
> <https://camo.githubusercontent.com/e324b2d14ad3f0153f14136b1ca84297581567ce/687474703a2f2f692e696d6775722e636f6d2f656d7a4e6578552e706e67>
> After:
>
> <https://camo.githubusercontent.com/28a5d831e20200eefe3db1faa6e57df92ec08910/687474703a2f2f692e696d6775722e636f6d2f4d43516978476c2e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-101659278>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
@DeviantInterface, I disagree... :smile:

**Comment by DeviantInterface** [comment]
Wide. Sorry, wide. It's still morning, and I woke up at 5:30 AM

On Wed, May 13, 2015 at 9:12 AM, Rodrigo Graça <notifications@github.com>
wrote:

> @DeviantInterface <https://github.com/DeviantInterface>, I disagree... [image:
> :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-101677719>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by DeviantInterface** [comment]
Could you make a .gif of the template? (The Fading Triangle/ Line/
Background)

On Wed, May 13, 2015 at 10:16 AM, Deviant Interface <
halokid687doesminecraft@gmail.com> wrote:

> Wide. Sorry, wide. It's still morning, and I woke up at 5:30 AM
>
> On Wed, May 13, 2015 at 9:12 AM, Rodrigo Graça <notifications@github.com>
> wrote:
>
>> @DeviantInterface <https://github.com/DeviantInterface>, I disagree... [image:
>> :smile:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-101677719>
>> .
>>
>
>
>
> --
> ///Deviant
> Name: Mccree, Daniel P.
> SSN: XXX-XX-2840
> Designation: Threat To System
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
@DeviantInterface a .gif of just the triangle?

**Comment by DeviantInterface** [comment]
Yeaaaa

On Wednesday, May 20, 2015, Rodrigo Graça <notifications@github.com> wrote:

> @DeviantInterface <https://github.com/DeviantInterface> a .gif of just
> the triangle?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-103987644>
> .
>


-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
No.
AFAIK .gif does not allow transparency, so it would not make sense...
BTW, I think some people already done it on the Person of Interest subreddit...

**Comment by DeviantInterface** [comment]
Yea, but it's only the black version, I've been after a white version for
months

On Wed, May 20, 2015 at 2:31 PM, Rodrigo Graça <notifications@github.com>
wrote:

> No.
> AFAIK .gif does not allow transparency, so it would not make sense...
> BTW, I think some people already done it on the Person of Interest
> subreddit...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-104007114>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by DeviantInterface** [comment]
How would you make a gif of that?

On Wed, May 20, 2015 at 2:35 PM, Deviant Interface <
halokid687doesminecraft@gmail.com> wrote:

> Yea, but it's only the black version, I've been after a white version for
> months
>
> On Wed, May 20, 2015 at 2:31 PM, Rodrigo Graça <notifications@github.com>
> wrote:
>
>> No.
>> AFAIK .gif does not allow transparency, so it would not make sense...
>> BTW, I think some people already done it on the Person of Interest
>> subreddit...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-104007114>
>> .
>>
>
>
>
> --
> ///Deviant
> Name: Mccree, Daniel P.
> SSN: XXX-XX-2840
> Designation: Threat To System
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
@DeviantInterface the only way I see would be to capture it in video and them transform the video to gif...

**Comment by DeviantInterface** [comment]
Joy. I'll see what I can do

On Thu, May 21, 2015 at 11:27 AM, Rodrigo Graça <notifications@github.com>
wrote:

> @DeviantInterface <https://github.com/DeviantInterface> the only way I
> see would be to capture it in video and them transform the video to gif...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-104343992>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by DeviantInterface** [comment]
Wait, what's the issue with making a gif out of it now??

On Thu, May 21, 2015 at 11:33 AM, Deviant Interface <
halokid687doesminecraft@gmail.com> wrote:

> Joy. I'll see what I can do
>
> On Thu, May 21, 2015 at 11:27 AM, Rodrigo Graça <notifications@github.com>
> wrote:
>
>> @DeviantInterface <https://github.com/DeviantInterface> the only way I
>> see would be to capture it in video and them transform the video to gif...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-104343992>
>> .
>>
>
>
>
> --
> ///Deviant
> Name: Mccree, Daniel P.
> SSN: XXX-XX-2840
> Designation: Threat To System
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
?

**Comment by DeviantInterface** [comment]
You said earlier you couldn't do it, why?

On Thu, May 21, 2015 at 1:05 PM, Rodrigo Graça <notifications@github.com>
wrote:

> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-104373898>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
@DeviantInterface because other people have already done it, for example:
http://static.tumblr.com/2f466dadd3b25fd93f2824e1c32e4bc4/zdng6g7/gnDnf0gz5/tumblr_static_akm35aynoiok8g4k4w44g00o4.gif

**Comment by DeviantInterface** [comment]
Oh

On Thu, May 21, 2015 at 1:26 PM, Rodrigo Graça <notifications@github.com>
wrote:

> @DeviantInterface <https://github.com/DeviantInterface> because other
> people have already done it, for example:
>
> http://static.tumblr.com/2f466dadd3b25fd93f2824e1c32e4bc4/zdng6g7/gnDnf0gz5/tumblr_static_akm35aynoiok8g4k4w44g00o4.gif
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-104378498>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by DeviantInterface** [comment]
Nono, I mean just the triangle fading and reappearing

On Thu, May 21, 2015 at 1:35 PM, Deviant Interface <
halokid687doesminecraft@gmail.com> wrote:

> Oh
>
> On Thu, May 21, 2015 at 1:26 PM, Rodrigo Graça <notifications@github.com>
> wrote:
>
>> @DeviantInterface <https://github.com/DeviantInterface> because other
>> people have already done it, for example:
>>
>> http://static.tumblr.com/2f466dadd3b25fd93f2824e1c32e4bc4/zdng6g7/gnDnf0gz5/tumblr_static_akm35aynoiok8g4k4w44g00o4.gif
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rodrigograca31/Samaritan/pull/9#issuecomment-104378498>
>> .
>>
>
>
>
> --
> ///Deviant
> Name: Mccree, Daniel P.
> SSN: XXX-XX-2840
> Designation: Threat To System
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Pull request merged**
