### PR TITLE
Update phraselist.js

### PR DESCRIPTION
**Pull request by Vezzeract**

### CODE REVIEW

**Comment by Feliix42** [comment]
Why? Where are those phrases coming from? Can't remember having seen them on the series.

**Comment by rodrigograca31** [comment]
I agree with @Feliix42 and I will not accept this Pull Request.... ;(

**Comment by ChemiKhazi** [comment]
I'd be more comfortable with getting this pull request deleted somehow, since it seems to include real people's names and partial address and this is a public repo. @Vezzeract is it possible for you to delete the branch from your side?

**Comment by rodrigograca31** [comment]
@ChemiKhazi I didn't even thought about that.... 
From what I can see only he (@Vezzeract) will be able to delete it....

**Comment by ChemiKhazi** [comment]
I've sent an email to GitHub support requesting that they delete the pull request.

**Comment by rodrigograca31** [comment]
@ChemiKhazi Good idea.... Thanks!

**Pull request closed without merging**
