### PR TITLE
Changed the blinking triangle to a blinking cursor to match the new S5 opening

### PR DESCRIPTION
**Pull request by MightyAlex200**

### CODE REVIEW

**Comment by rodrigograca31** [comment]
I would accept this, but.....
Yes it's the new way.... but you used `requestAnimationFrame` which runs that code "millions of times"....
It could/should use the previous method (timeouts) ....

Comments?

**Comment by MightyAlex200** [comment]
Doesn't `requestAnimationFrame`only run code at 60fps max, and will slow itself down if the tab is in the background, or there isn't enough processing power? I read it on the Mozilla Developer Network: [https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame](url)

**Comment by rodrigograca31** [comment]
Yheaa.... When I said "millions of times" I meant the 60fps....

Meh.... I will accept the pull request....

**Comment by rodrigograca31** [comment]
Just saw that the page was not updated and took care of it:

[http://rodrigograca31.github.io/Samaritan/](http://rodrigograca31.github.io/Samaritan/)

**Comment by rodrigograca31** [comment]
Hi @MightyAlex200 unfortunately I'm reverting your pull request.... If you saw the last episode we can clearly see that it's the triangle that blinks..... 

"Sorry" :(

**Pull request merged**
