### PR TITLE
speech recognition

### PR DESCRIPTION
**Pull request by AlexandruSimandi**
Works perfectly in chrome, did not test in other browsers supporting microphone but the API promises to work. There might be a problem with the service worker because i had to ctrl+f5 a couple times. Isn't it overkill to cache?
[Live version](https://alexandrusimandi.github.io/Samaritan/)
What you can say:
* yes
* no
* hello
* who are you
* what are you
* turn off
* restart
* who created you
* who won
* say my name
* find < name >
* search (for) < name >
* any combination of 1-3 words such as "couch potato", "I like cats"

### CODE REVIEW

**Comment by rodrigograca31** [comment]
I love it! :)

Thanks for the contribution!

Yheaa the service worker is a bit overkill, I was experimenting with the hype of Progressive Web Apps that Google "announced" on Google IO this year because this was my "pet project" and because it works as an app on a Phone....

I will just update my page and the readme file.

Thanks!

**Comment by rodrigograca31** [comment]
@AlexandruSimandi do you have an Reddit username?

**Comment by rodrigograca31** [comment]
Forget my question... I've seen your reddit comment...

**Comment by AdminOdd** [comment]
You are a Freaking Fu*King Genius GOD FREAKIN BLESS U MAN!

On Thu, Jun 23, 2016 at 3:56 PM, Alexandru Simandi <notifications@github.com

**Pull request merged**
