### PR TITLE
Manually merged with base changes and my changes

### PR DESCRIPTION
**Pull request by AlexandruSimandi**
- boot animation
- check for browser speech recognition
- major refactoring

I manually merged with all your changes until Jun 27, 2016.
You can directly override on your base.
[live](https://alexandrusimandi.github.io/Samaritan/)

Check the coding style if you like it. I found it necessary to get rid of global variabiles. Also renamed #_executeSamaritan_ into #_write_ since it was unclear. Use _samaritanModule.write(txt)_ to make samaritan say txt.

Now there is one single  $(document).ready and that is in the new file _main.js_

## Don't forget the readme :smile:

### CODE REVIEW

**Comment by rodrigograca31** [comment]
"This branch has conflicts that must be resolved" .... I need to take a closer look at this before approving the changes....

I'm still at work... I will take a closer look later...

**Comment by AlexandruSimandi** [comment]
That's the point of a manual merge...

**Comment by rodrigograca31** [comment]
All changes were merged! :)

**Comment by AlexandruSimandi** [comment]
Actually not. It's still the old version of _speech.js_ and _samaritan.js_

**Comment by rodrigograca31** [comment]
You are right....
I will just copy and past your repo.....

**Comment by AlexandruSimandi** [comment]
I am also not sure about the font url which one is the good one.

**Comment by rodrigograca31** [comment]
Hey @AlexandruSimandi I've just manually merged your repo.

**Pull request merged**
