### PR TITLE
Master

### PR DESCRIPTION
**Pull request by DeviantInterface**
Added 2 phrases

### CODE REVIEW

**Comment by rodrigograca31** [comment]
:thumbsup:

**Comment by DeviantInterface** [comment]
What??

On Friday, May 8, 2015, Rodrigo Graça <notifications@github.com> wrote:

> [image: :thumbsup:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/8#issuecomment-100356969>
> .
>


-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
@DeviantInterface I was just liking the fact that the project was updated. ;) (github...)

**Comment by DeviantInterface** [comment]
Oh. I can't sync it tbo

On Friday, May 8, 2015, Rodrigo Graça <notifications@github.com> wrote:

> @DeviantInterface <https://github.com/DeviantInterface> I was just liking
> the fact that the project was updated. ;) (github...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/8#issuecomment-100365477>
> .
>


-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
Why can't you sync it? Its probably a git problem... Right? We can't help you with that here, but the best option is to delete the repo and download it again.....

**Comment by DeviantInterface** [comment]
It said something about permissions

On Friday, May 8, 2015, Rodrigo Graça <notifications@github.com> wrote:

> Why can't you sync it? Its probably a git problem... Right? We can't help
> you with that here, but the best option is to delete the repo and download
> it again.....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/8#issuecomment-100380539>
> .
>


-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
@DeviantInterface :frowning: ... Yheaa, you don't have direct write permisions to this repo, you need to fork it, commit your changes and then send a pull request, you can find [more info here](https://help.github.com/articles/using-pull-requests/).

**Comment by DeviantInterface** [comment]
Great.... I sent a pull request

On Sat, May 9, 2015 at 2:08 PM, Rodrigo Graça <notifications@github.com>
wrote:

> @DeviantInterface <https://github.com/DeviantInterface> [image:
> :frowning:] ... Yheaa, you don't have direct write permisions to this
> repo, you need to fork it, commit your changes and then send a pull
> request, you can find more info here
> <https://help.github.com/articles/using-pull-requests/>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/8#issuecomment-100530588>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by rodrigograca31** [comment]
Are you sure? I don't see anything...

It should be here: https://github.com/rodrigograca31/Samaritan/pulls

**Comment by DeviantInterface** [comment]
I'll send it again later

On Tue, May 12, 2015 at 1:14 PM, Rodrigo Graça <notifications@github.com>
wrote:

> Are you sure? I don't see anything...
>
> It should be here: https://github.com/rodrigograca31/Samaritan/pulls
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rodrigograca31/Samaritan/pull/8#issuecomment-101372266>
> .
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by DeviantInterface** [comment]
Alright, I sent it

On Tue, May 12, 2015 at 1:22 PM, Deviant Interface <
halokid687doesminecraft@gmail.com> wrote:

> I'll send it again later
>
> On Tue, May 12, 2015 at 1:14 PM, Rodrigo Graça <notifications@github.com>
> wrote:
>
>> Are you sure? I don't see anything...
>>
>> It should be here: https://github.com/rodrigograca31/Samaritan/pulls
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rodrigograca31/Samaritan/pull/8#issuecomment-101372266>
>> .
>>
>
>
>
> --
> ///Deviant
> Name: Mccree, Daniel P.
> SSN: XXX-XX-2840
> Designation: Threat To System
>



-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Pull request merged**
